export const dom = {
  canvasRoot: document.getElementById('canvas-root'),
  messages: document.getElementById('messages'),
  template: document.getElementById('message-template'),
  input: document.getElementById('input'),
  send: document.getElementById('send'),
  mic: document.getElementById('mic'),
  liveMode: document.getElementById('live-mode'),
  newChat: document.getElementById('new-chat'),
  statusText: document.getElementById('status-text'),
  statusDot: document.getElementById('status-dot'),
  runtimeModel: document.getElementById('runtime-model'),
  runtimeTts: document.getElementById('runtime-tts'),
  voiceSelect: document.getElementById('voice-select'),
  modelFile: document.getElementById('model-file'),
};
